# Generated by Django 4.1.1 on 2023-07-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('complete', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
